//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::account::Entity as Account;
pub use super::author::Entity as Author;
pub use super::music::Entity as Music;
pub use super::progress::Entity as Progress;
